declare const NEXT_PUBLIC_SUPABASE_URL: string;
declare const NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
declare const SUPABASE_SERVICE_KEY: string;
declare const RAINDROP_CLIENT_ID: string;
declare const RAINDROP_CLIENT_SECRET: string;
declare const ENDPOINT: string;
declare const RAINDROP_CACHE: KVNamespace;
declare const ENABLED_APP: 'true' | 'false';
declare const EXPIRED_ACCESS_TOKEN: string | undefined;
declare const PUDDLE_ACCESS_TOKEN: string | undefined;
