name = "puddle"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

kv_namespaces = [
  { binding = "RAINDROP_CACHE", id = "1af025d4e6bb4aca9206d07805d02558" }
]

[vars]
ENDPOINT = "http://localhost:4200"
ENABLED_APP = 'true'

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[env.production.vars]
ENDPOINT = "https://puddle-production.digital-shuufei.workers.dev"
ENABLED_APP = 'false'

[env.production]
kv_namespaces = [
  { binding = "RAINDROP_CACHE", id = "1af025d4e6bb4aca9206d07805d02558" }
]
